### ISSUE TITLE
全网发布时不通过

### ISSUE THREAD

**Issue by TonyLuo** [Wechat-Group/weixin-java-open-demo#1]
名称 | 状态
-- | --
[组件ticket正确接收] | 成功
[生成预授权码] | 成功
[获取授权code] | 成功
[授权] | 成功
[返回Api文本消息] | 失败
[返回普通文本消息] | 成功
[发送事件消息] | 失败
[取消授权] | 成功

查看log时发现authorizer_refresh_token 是null，不知道是不是有影响

2018-03-20 15:41:25,647 ERROR [XNIO-2 task-13] WxOpenServiceDemo:
【请求地址】: https://api.weixin.qq.com/cgi-bin/component/api_authorizer_token?component_access_token=token
【请求参数】：{"component_appid":"component_appid","authorizer_appid":"authorizer_appid","authorizer_refresh_token":null}
【错误信息】：{"errcode":61023,"errmsg":"refresh_token is invalid hint: [458N06852994]"}
2018-03-20 15:41:25,647 ERROR [XNIO-2 task-13] NotifyController: callback
me.chanjar.weixin.common.exception.WxErrorException: {"errcode":61023,"errmsg":"refresh_token is invalid hint: [458N06852994]"}

**Comment by 007gzs** [comment]
LOG是你截图的么？所有参数都不对啊，
{"component_appid":"component_appid","authorizer_appid":"authorizer_appid","authorizer_refresh_token":null}
这些应该都是对应的APPID才对啊，你的ConfigStorage怎么设置的？

**Comment by TonyLuo** [comment]
"component_appid和"authorizer_appid"," 做了修改，因为不想把这些信息发到网上

**Comment by TonyLuo** [comment]
这个项目就是修改了对应的appid和redis的服务器地址，其他都没怎么改
 @PostConstruct
    public void init() {
        WxOpenInRedisConfigStorage inRedisConfigStorage = new WxOpenInRedisConfigStorage(getJedisPool());
        inRedisConfigStorage.setComponentAppId(wechatOpenProperties.getComponentAppId());
        inRedisConfigStorage.setComponentAppSecret(wechatOpenProperties.getComponentSecret());
        inRedisConfigStorage.setComponentToken(wechatOpenProperties.getComponentToken());
        inRedisConfigStorage.setComponentAesKey(wechatOpenProperties.getComponentAesKey());
        setWxOpenConfigStorage(inRedisConfigStorage);

**Comment by 007gzs** [comment]
授权回调内容是按照DEMO里的么

**Comment by 007gzs** [comment]
确认下  String out = wxOpenService.getWxOpenComponentService().route(inMessage); 这行是否正确执行

**Comment by TonyLuo** [comment]
多试几次又可以了。不知道是不是开放平台的问题

**Comment by ForeverIkaros** [comment]
发送事件消息进不去怎么破？
