### ISSUE TITLE
在handler中return WxMpXmlOutMessage，微信公众号提示：该公众号提供的服务出现故障

### ISSUE THREAD

**Issue by AlanMathisonTuring** [Wechat-Group/weixin-java-open-demo#10]
三方平台授权，我在handler中接收到用户消息后，返回WxMpXmlOutMessage文字消息或图片消息，都提示“该公众号提供的服务出现故障”，请问是哪里还需要配置么？之前使用weixin-java-tools从未出现过该现象。

**Comment by AlanMathisonTuring** [comment]
嗯，感谢回复，我直接拿DEMO说吧
======================第一部分代码  START=======================
@RequestMapping("{appId}/callback")
    public Object callback(@RequestBody(required = false) String requestBody,
                           @PathVariable("appId") String appId,
                           @RequestParam("signature") String signature,
                           @RequestParam("timestamp") String timestamp,
                           @RequestParam("nonce") String nonce,
                           @RequestParam("openid") String openid,
                           @RequestParam("encrypt_type") String encType,
                           @RequestParam("msg_signature") String msgSignature) {
        this.logger.info(
                "\n接收微信请求：[appId=[{}], openid=[{}], signature=[{}], encType=[{}], msgSignature=[{}],"
                        + " timestamp=[{}], nonce=[{}], requestBody=[\n{}\n] ",
                appId, openid, signature, encType, msgSignature, timestamp, nonce, requestBody);
        if (!StringUtils.equalsIgnoreCase("aes", encType)
                || !wxOpenService.getWxOpenComponentService().checkSignature(timestamp, nonce, signature)) {
            throw new IllegalArgumentException("非法请求，可能属于伪造的请求！");
        }

        String out = "";
        // aes加密的消息
        WxMpXmlMessage inMessage = WxOpenXmlMessage.fromEncryptedMpXml(requestBody,
                wxOpenService.getWxOpenConfigStorage(), timestamp, nonce, msgSignature);
        this.logger.debug("\n消息解密后内容为：\n{} ", inMessage.toString());
        
        WxMpXmlOutMessage outMessage = wxOpenService.getWxOpenMessageRouter().route(inMessage, appId);

         System.out.println("--------------------测试-------");
        if(outMessage != null){
            out = WxOpenXmlMessage.wxMpOutXmlMessageToEncryptedXml(outMessage, wxOpenService.getWxOpenConfigStorage());
        }
        
        return out;
    }
=============================第一部分代码  END=======================
上面部分代码是第三方平台公众号授权成功后用户交互后收到消息然后设置路由

=============================第二部分代码  Start=======================
 @PostConstruct
    public void init() {
        WxOpenInRedisConfigStorage inRedisConfigStorage = new WxOpenInRedisConfigStorage(getJedisPool());
        inRedisConfigStorage.setComponentAppId(wechatOpenProperties.getComponentAppId());
        inRedisConfigStorage.setComponentAppSecret(wechatOpenProperties.getComponentSecret());
        inRedisConfigStorage.setComponentToken(wechatOpenProperties.getComponentToken());
        inRedisConfigStorage.setComponentAesKey(wechatOpenProperties.getComponentAesKey());
        setWxOpenConfigStorage(inRedisConfigStorage);
        wxOpenMessageRouter = new WxOpenMessageRouter(this);
        wxOpenMessageRouter.rule().handler((wxMpXmlMessage, map, wxMpService, wxSessionManager) -> {
            logger.info("\n接收到 {} 公众号请求消息，内容：{}", wxMpService.getWxMpConfigStorage().getAppId(), wxMpXmlMessage);
            
            String content = "您好！";
            WxMpKefuMessage kefuMessage = WxMpKefuMessage.TEXT().content(content).toUser(wxMpXmlMessage.getFromUser()).build();
			wxMpService.getKefuService().sendKefuMessage(kefuMessage);
            
            return WxMpXmlOutMessage.TEXT().content(content)
				        .fromUser(wxMpXmlMessage.getToUser()).toUser(wxMpXmlMessage.getFromUser())
				        .build();
        }).next();
    }
=============================第二部分代码  END=======================

第二部分代码重的客服消息发送  “您好！”  能收到，但是return的消息没有到用户端，并且用户端显示“该公众号服务受限”，并且！第一部分代码重的 "--------------------测试-------"没有打印出来。

服务器后台日志没有任何报错

**Comment by 007gzs** [comment]
--------------------测试------- 没打出来说明没进入callback，看下accesslog，确实是不是真的没请求callback，如果没请求的话看开放平台配置的是否正确

**Comment by AlanMathisonTuring** [comment]
能打印，现在遇到一个比较奇怪的问题，在callback中，返回XML格式的文字消息，用户端是可以收到回复的消息，但是直接回复""或者直接回复"success"，用户端显示"该公众号服务出现故障"
看微信文档中好像是直接可以直接这样回复的啊？
1、直接回复success（推荐方式） 2、直接回复空串（指字节长度为0的空字符串，而不是XML结构体中content字段的内容为空）

**Comment by evansacred** [comment]
楼主在吗，我也碰到提示“该公众号提供的服务出现故障”的问题了，问下您当时是怎么解决的？
