### ISSUE TITLE
管理员扫码后出现错误

### ISSUE THREAD

**Issue by MurcielagoAN** [Wechat-Group/weixin-java-open-demo#12]
已经添加测试公众号列表，但是管理员扫码后依然出现请全网发布或将尝试授权的公众号或小程序添加到授权测试公众号列表后再试

**Comment by binarywang** [comment]
@007gzs

**Comment by 007gzs** [comment]
先确认下你测试公众号列表里写的公众号原始ID是否正确

**Comment by MurcielagoAN** [comment]
原始ID已经确认多次，正确的，gh_开头的一个，是没问题的
@007gzs

**Comment by chz102** [comment]
我也有同样的问题，@MurcielagoAN 解决了吗？

**Comment by 007gzs** [comment]
今天碰到群里另一位遇到这个问题，扫码的微信需要是测试公众号的管理员，你们确认下是不是扫码微信不是管理员 @MurcielagoAN @chz102
