### ISSUE TITLE
开放平台api地址变了吗

### ISSUE THREAD

**Issue by shonve** [Wechat-Group/weixin-java-open-demo#14]
我在开发平台文档看到请求token的地址是：https://api.weixin.qq.com/sns/oauth2/access_token?appid=APPID&secret=SECRET&code=CODE&grant_type=authorization_code

可是这个项目里面并没有请求这个地址的方法，请问是怎么回事呢？
我看到相关接口的url都在这里，并没有文档中心的接口地址
![image](https://user-images.githubusercontent.com/12680137/56178172-dc789780-6033-11e9-9229-643b5c7e999c.png)

**Comment by binarywang** [comment]
因为这个接口比较简单，初期就实现了，只不过是在mp 公众号模块里的，本SDK中的开放平台模块暂不关注这个接口

**Comment by binarywang** [comment]
自己在源码里搜索就能找到

**Comment by shonve** [comment]
ok，多谢，那我到公众号模块去看看
