### ISSUE TITLE
开放平台的网站应用不可以用吗

### ISSUE THREAD

**Issue by zeemood** [Wechat-Group/weixin-java-open-demo#15]
RT

**Comment by binarywang** [comment]
能否描述详细些？比如你要实现的功能的准确官方名称或者其对应文档地址

**Comment by zeemood** [comment]
https://open.weixin.qq.com/cgi-bin/showdocument?action=dir_list&t=resource/res_list&verify=1&id=open1419316505&token=&lang=zh_CN
就是单纯的网站登录

**Comment by binarywang** [comment]
请参考WxMpService里的方法，由于实现的比较早，在mp模块里先实现了的
