### ISSUE TITLE
ComponentAccessToken过期了不会自动刷新

### ISSUE THREAD

**Issue by TonyLuo** [Wechat-Group/weixin-java-open-demo#2]
demo运行时间比较长，会出现下面的错误
{"errcode":40001,"errmsg":"invalid credential, access_token is invalid or not latest hint: [XLAiDa03434521]"}

**Comment by 007gzs** [comment]
修改了
https://github.com/Wechat-Group/weixin-java-tools/pull/547
另外，这个问题不是demo的问题，issues最好上到 weixin-java-tools 上
