### ISSUE TITLE
需要@Autowired注入WxOpenMaService怎么配置

### ISSUE THREAD

**Issue by gus-liu** [Wechat-Group/weixin-java-open-demo#22]
示例提供的WxOpenServiceDemo注入没有问题。
但是要使用WxOpenMaService的话怎么注入配置呢？
看到实现类的构造方法是 WxOpenMaServiceImpl(WxOpenComponentService wxOpenComponentService, String appId, WxMaConfig wxMaConfig)

**Comment by binarywang** [comment]
首先，要想autowire，你首先得让spring管理对应bean，这是spring基础问题。
其次，如果这个类的构造方法里没有，就说明它不需要，你如果需要，就是需要自己写新的代码。
