### ISSUE TITLE
全网发布出错。【组件ticket正确接收】 失败

### ISSUE THREAD

**Issue by qcran** [Wechat-Group/weixin-java-open-demo#24]
【组件ticket正确接收】 失败
【返回Api文本消息】成功
【返回普通文本消息】失败
这个怎么解决呢？发现有调用6次/receive_ticket 都返回了“success”

**Comment by binarywang** [comment]
@007gzs 有空可以帮忙看下

**Comment by qichaoran** [comment]
> 
> 
> @007gzs 有空可以帮忙看下

解决了，ticket可能是controller返回方式的问题（使用PrintWriter），普通文本跟api文本消息一样的也调用客服接口并返回这个字符串？就可以了（也不知道是客服调用还是返回值成功的）。。。有点郁闷，
WxMpKefuMessage kefuMessage = WxMpKefuMessage.TEXT().content("TESTCOMPONENT_MSG_TYPE_TEXT_callback").toUser(inMessage.getFromUser()).build();                       wechatService.getWxOpenComponentService().getWxMpServiceByAppid(appId).getKefuService().sendKefuMessage(kefuMessage);
return kefuMessage.getContent();
