### ISSUE TITLE
集群部署

### ISSUE THREAD

**Issue by lmj2577977814** [Wechat-Group/weixin-java-open-demo#36]
集群部署的话,相同的第三方平台配置,会不会有accessToken失效的问题啊, 怎么解决呢

**Comment by binarywang** [comment]
使用redis相关配置

**Comment by lmj2577977814** [comment]
我看demo理由有使用redis,请问现在demo这套代码可以直接用吗,还是说需要将一些其他的存到redis里面, 比如WxOpenServiceDemo wxOpenServiceDemo, 麻烦说的具体点,谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wechat-Group/weixin-java-open-demo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月2日(星期三) 下午5:34
收件人:&nbsp;"Wechat-Group/weixin-java-open-demo"<weixin-java-open-demo@noreply.github.com&gt;;
抄送:&nbsp;"...."<2577977814@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Wechat-Group/weixin-java-open-demo] 集群部署 (#36)





 
使用redis相关配置

**Comment by binarywang** [comment]
这个demo只是内置了部分基础redis代码，你如果要使用可能还需要加点其他配置，具体根据你的需求而定。
本demo主要是演示如何使用WxJava里的的sdk接口请求微信接口

**Comment by lmj2577977814** [comment]
好的,了解,谢了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Wechat-Group/weixin-java-open-demo"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月4日(星期五) 上午10:23
收件人:&nbsp;"Wechat-Group/weixin-java-open-demo"<weixin-java-open-demo@noreply.github.com&gt;;
抄送:&nbsp;"...."<2577977814@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Wechat-Group/weixin-java-open-demo] 集群部署 (#36)





 
这个demo只是内置了部分基础redis代码，你如果要使用可能还需要加点其他配置，具体根据你的需求而定。
 本demo主要是演示如何使用WxJava里的的sdk接口请求微信接口
