### ISSUE TITLE
org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 9; 文件提前结束

### ISSUE THREAD

**Issue by Doing-code** [Wechat-Group/weixin-java-open-demo#41]
授权的时候. 报这个错误, 请问是什么情况? 该怎么解决呢

me.chanjar.weixin.common.error.WxRuntimeException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 9; 文件提前结束。

// aes加密的消息
        WxOpenXmlMessage inMessage = WxOpenXmlMessage.fromEncryptedXml(requestBody,
                wxOpenService.getWxOpenConfigStorage(), timestamp, nonce, msgSignature);

Caused by: org.xml.sax.SAXParseException: 文件提前结束。

**Comment by Doing-code** [comment]
用测试Demo没问题，但移到自己项目下使用 ，requestBody 是空 ""

**Comment by binarywang** [comment]
肯定是你所使用的框架的一些通用配置导致的

**Comment by CV12138** [comment]
我也遇到了这个问题，因为我使用的框架默认开启了xss过滤，当我放行了这个接口后就可以正常获取到requestBody参数
