### ISSUE TITLE
运行demo推送ticket的时候报错

### ISSUE THREAD

**Issue by Stulcc** [Wechat-Group/weixin-java-open-demo#5]
{"timestamp":"Jul 2, 2018 6:18:59 PM","status":500,"error":"Internal Server Error","exception":"java.lang.RuntimeException","message":"org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; 前言中不允许有内容。","path":"/notify/receive_ticket"}，调试发现WxCryptUtil类的bytesNetworkOrder2Number方法直接返回负数

**Comment by 007gzs** [comment]
是接收微信的回调报错的么？看下设置有没有问题。
bytesNetworkOrder2Number是网络字节序转本地字节序，返回负数正常

**Comment by Stulcc** [comment]
昨天不行，我记得我换过了那两个加密的包，今天我又换了一次，可以了。谢谢回复。
