### ISSUE TITLE
WxMpTemplateMsgService类的addTemplate少参数

### ISSUE THREAD

**Issue by mashining1988111** [Wechat-Group/weixin-java-open-demo#52]
WxMpTemplateMsgService类的addTemplate只有一个参数，官方文档有两个参数

https://developers.weixin.qq.com/doc/offiaccount/Message_Management/Template_Message_Interface.html#%E8%8E%B7%E5%BE%97%E6%A8%A1%E6%9D%BFID

![image](https://github.com/Wechat-Group/weixin-java-open-demo/assets/12853767/9ec3aa07-f60b-4e94-ac6a-2b05fc8fbd7f)

**Comment by binarywang** [comment]
麻烦提交issue到wxjava中，谢谢

**Comment by binarywang** [comment]
这个其实最新版已经加上了
