### ISSUE TITLE
怎么支持多个第三方平台?

### ISSUE THREAD

**Issue by gclsoft** [Wechat-Group/weixin-java-open-demo#6]
![image](https://user-images.githubusercontent.com/1269898/42754224-482dd750-8926-11e8-9ab1-5d124e63f766.png)
配置成多个账号的第三方平台可以吗? 有没有例子,谢谢!
因为主体不一样, 是不能直接获取unionid的,所以我们申请了多个第三方平台

**Comment by jokester** [comment]
简单看了下，这个demo的配置只是给内部WxOpenServiceDemo用的，要改代码才能配置成多个第三方平台。

下面的 `weixin-java-open ` 等lib没有限制第三方平台的数量。

**Comment by binarywang** [comment]
可以参考mp\cp等其他模块的demo，有支持多账号的解决方案

**Comment by zeemood** [comment]
开放平台的网站应用不可以用吗？为什么跟公众号有关了？

**Comment by binarywang** [comment]
> 开放平台的网站应用不可以用吗？为什么跟公众号有关了？

与本问题无关的问题，请单独提出，不要在这里提出，谢谢配合
