### ISSUE TITLE
DEMO中公众号发送TESTCOMPONENT_MSG_TYPE_TEXT，显示该公众号提供的服务出现故障，是哪里配置错了吗？

### ISSUE THREAD

**Issue by kyne0116** [Wechat-Group/weixin-java-open-demo#9]
DEMO跑起来以后，后台未见任何异常，就是给授权过的测试公众号发送文本消息“TESTCOMPONENT_MSG_TYPE_TEXT”，没有收到预期的“TESTCOMPONENT_MSG_TYPE_TEXT_callback”，提示该公众号提供的服务出现故障，请问是哪里配置错误了呢？

**Comment by AlanMathisonTuring** [comment]
我也遇到了该问题，在handler中处理接收到的事件或用户消息后直接返回WxMpXmlOutMessage，公众号提示“该公众号提供的服务出现故障”，请问您解决这问题了么？

**Comment by Bleach4Ever** [comment]
有可能是公众号在其他地方也做了回调接入哦
